namespace Harken.Core;

/// <summary>
/// A Summary generated by the Summarize Agent, persisted so it can be re-read
/// instead of regenerated on every request. One per Session.
/// Ownership is inherited through the Session.
/// </summary>
public class StoredSummary
{
    public Guid Id { get; set; }
    public Guid SessionId { get; set; }
    public string Text { get; set; } = string.Empty;
    public DateTimeOffset GeneratedAt { get; set; }
}
