<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Harken.Core\Harken.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime.Cuda.Windows" />
  </ItemGroup>

  <PropertyGroup>
    <UserSecretsId>94fb94ee-c998-4d28-bdef-846383b3009b</UserSecretsId>
  </PropertyGroup>

</Project>
