// <auto-generated />
using System;
using Harken.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harken.Api.Migrations
{
    [DbContext(typeof(HarkenDbContext))]
    [Migration("20260821133519_AddSessionDeletedFlag")]
    partial class AddSessionDeletedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Harken.Core.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("Harken.Core.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientRecordingId")
                        .IsUnique()
                        .HasFilter("\"ClientRecordingId\" IS NOT NULL");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Harken.Core.StoredSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("StoredSummaries");
                });

            modelBuilder.Entity("Harken.Core.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecognizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TranscriptSegments");
                });

            modelBuilder.Entity("Harken.Core.Recording", b =>
                {
                    b.HasOne("Harken.Core.Session", null)
                        .WithOne("Recording")
                        .HasForeignKey("Harken.Core.Recording", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Harken.Core.StoredSummary", b =>
                {
                    b.HasOne("Harken.Core.Session", null)
                        .WithOne()
                        .HasForeignKey("Harken.Core.StoredSummary", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Harken.Core.TranscriptSegment", b =>
                {
                    b.HasOne("Harken.Core.Session", null)
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Harken.Core.Session", b =>
                {
                    b.Navigation("Recording");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
